//go:build ignore

// 把旁边的 Go 应用编成可 file:// 打开的静态站点，产物落在 web/dist。
//
// 约定：本文件放在 {app}/web/build_web.go，应用入口是 {app}（含 main.go）；拷到别的
// 应用（如 clicktest/web/）后直接 go run ./{app}/web/build_web.go 即可，不必改脚本。
//
//	go run ./imgen/web/build_web.go
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

func main() {
	if err := build(); err != nil {
		fmt.Fprintf(os.Stderr, "build failed: %v\n", err)
		os.Exit(1)
	}
}

func build() error {
	webDir, err := thisDir()
	if err != nil {
		return err
	}
	appDir := filepath.Dir(webDir)
	app := filepath.Base(appDir)
	if app == "" || app == "." || app == string(filepath.Separator) {
		return fmt.Errorf("无法从 %s 推出应用目录（本文件应放在 {app}/web/）", webDir)
	}

	root, err := repoRoot(webDir)
	if err != nil {
		return err
	}
	pkg, err := pkgPath(root, appDir)
	if err != nil {
		return err
	}

	distDir := filepath.Join(webDir, "dist")
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		return err
	}

	wasmPath := filepath.Join(distDir, "app.wasm")
	fmt.Printf("[1/4] compile %s → app.wasm ...\n", pkg)
	// -trimpath 去掉编译机绝对路径，产物可复现。刻意不加 -ldflags="-s -w"：
	// 实测对 wasm 体积没有帮助，反而把栈回溯里的符号名抹掉。
	if err := goBuild(root, wasmPath, pkg); err != nil {
		return err
	}

	fmt.Println("[2/4] gzip+base64 app.wasm.js ...")
	jsPath := filepath.Join(distDir, "app.wasm.js")
	rawN, gzN, b64N, err := writeWasmJS(wasmPath, jsPath)
	if err != nil {
		return err
	}
	fmt.Printf("  wasm %s → gzip %s → base64 %s\n", fmtSize(rawN), fmtSize(gzN), fmtSize(b64N))

	fmt.Println("[3/4] copy wasm_exec.js ...")
	src, err := findWasmExecJS()
	if err != nil {
		return err
	}
	if err := copyFile(src, filepath.Join(distDir, "wasm_exec.js")); err != nil {
		return err
	}

	fmt.Println("[4/4] copy index.html ...")
	htmlSrc := filepath.Join(webDir, "index.html")
	if _, err := os.Stat(htmlSrc); err != nil {
		return fmt.Errorf("缺少 %s", htmlSrc)
	}
	if err := copyFile(htmlSrc, filepath.Join(distDir, "index.html")); err != nil {
		return err
	}

	fmt.Println("done.")
	fmt.Println()
	fmt.Println("应用:", app)
	fmt.Println("包:  ", pkg)
	fmt.Println("产物:", distDir)
	fmt.Println("  index.html")
	fmt.Println("  wasm_exec.js")
	fmt.Println("  app.wasm.js   （gzip+base64，file:// 可直接打开）")
	fmt.Println("  app.wasm      （原始 wasm，调试用）")
	fmt.Println()
	fmt.Println("本地预览：直接打开 dist/index.html（不必起 http 服务）")
	return nil
}

func thisDir() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("无法定位 build_web.go")
	}
	return filepath.Abs(filepath.Dir(file))
}

func pkgPath(root, appDir string) (string, error) {
	rel, err := filepath.Rel(root, appDir)
	if err != nil {
		return "", err
	}
	rel = filepath.ToSlash(rel)
	if rel == "" || rel == "." {
		return ".", nil
	}
	if strings.HasPrefix(rel, "..") {
		return "", fmt.Errorf("应用目录 %s 不在模块根 %s 下", appDir, root)
	}
	return "./" + rel, nil
}

func writeWasmJS(wasmPath, jsPath string) (rawN, gzN, b64N int, err error) {
	raw, err := os.ReadFile(wasmPath)
	if err != nil {
		return 0, 0, 0, err
	}
	var gz bytes.Buffer
	zw, err := gzip.NewWriterLevel(&gz, gzip.BestCompression)
	if err != nil {
		return 0, 0, 0, err
	}
	if _, err := zw.Write(raw); err != nil {
		return 0, 0, 0, err
	}
	if err := zw.Close(); err != nil {
		return 0, 0, 0, err
	}
	b64 := base64.StdEncoding.EncodeToString(gz.Bytes())
	var buf bytes.Buffer
	buf.WriteString("// generated by build_web.go — gzip+base64 of app.wasm\n")
	buf.WriteString("var APP_WASM_GZ_B64 = \"")
	buf.WriteString(b64)
	buf.WriteString("\";\n")
	if err := os.WriteFile(jsPath, buf.Bytes(), 0o644); err != nil {
		return 0, 0, 0, err
	}
	return len(raw), gz.Len(), buf.Len(), nil
}

func fmtSize(n int) string {
	const mb = 1024 * 1024
	if n >= mb {
		return fmt.Sprintf("%.1f MB", float64(n)/mb)
	}
	if n >= 1024 {
		return fmt.Sprintf("%.1f KB", float64(n)/1024)
	}
	return fmt.Sprintf("%d B", n)
}

func goBuild(root, out, pkg string) error {
	cmd := exec.Command("go", "build", "-trimpath", "-o", out, pkg)
	cmd.Dir = root
	cmd.Env = withEnv(os.Environ(), map[string]string{
		"GOOS":        "js",
		"GOARCH":      "wasm",
		"CGO_ENABLED": "0",
	})
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func withEnv(base []string, extra map[string]string) []string {
	skip := map[string]bool{}
	for k := range extra {
		skip[k] = true
	}
	out := make([]string, 0, len(base)+len(extra))
	for _, kv := range base {
		k, _, ok := strings.Cut(kv, "=")
		if ok && skip[k] {
			continue
		}
		out = append(out, kv)
	}
	for k, v := range extra {
		out = append(out, k+"="+v)
	}
	return out
}

func findWasmExecJS() (string, error) {
	goroot, err := goEnv("GOROOT")
	if err != nil {
		return "", err
	}
	candidates := []string{
		filepath.Join(goroot, "lib", "wasm", "wasm_exec.js"),
		filepath.Join(goroot, "misc", "wasm", "wasm_exec.js"),
	}
	for _, p := range candidates {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p, nil
		}
	}
	return "", fmt.Errorf("找不到 wasm_exec.js（GOROOT=%s）。Go 1.21+ 在 lib/wasm，更早的在 misc/wasm", goroot)
}

func goEnv(key string) (string, error) {
	cmd := exec.Command("go", "env", key)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("go env %s: %w", key, err)
	}
	return strings.TrimSpace(string(out)), nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func repoRoot(start string) (string, error) {
	starts := []string{start}
	if wd, err := os.Getwd(); err == nil {
		starts = append(starts, wd)
	}
	for _, s := range starts {
		dir := s
		for {
			if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
				return dir, nil
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
		}
	}
	return "", fmt.Errorf("找不到仓库根目录（go.mod）")
}
